doc: improve PR template
mantis-tec/.github pull request #2
Opened 2022-12-09 14:58 UTC by LoicFerrot

PR to improve the next PRs.

2022-12-09 15:00 UTC, kevinanschau requested changes

2022-12-09 15:00 UTC, kevinanschau commented on .github/pull_request_template.md
>    - [ ] Tests for the changes have been added (for bug fixes/features)
You changed the bullet points to H3 headers. Therefore, the body doesn't need to be indented anymore. Would you be so kind and remove the indentations?

2022-12-12 13:00 UTC, KevinSchwarzer approved these changes

2022-12-14 13:28 UTC, LoicFerrot commented
@kevinanschau I don't have the rights to merge this, sorry...

2022-12-14 13:29 UTC, merged